---
- hosts: all
  tasks:
    - name: creates users files
      file:
        path: /home/ec2-user/ansible-{{ item }}
        state: touch
      loop:
        - sammy
        - erika
        - brian

        #using loops 