---
- hosts: all
  become: yes
  vars:
    page_title: Cloudreach Landing Page
    page_description: This is my landing page description.
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: latest

    - name: Enable amazon-linux-extras packages
      shell: "amazon-linux-extras enable nginx1"


    - name: Install apache httpd
      yum:
        name: httpd
        update_cache: yes

    - name: Apply Page Template
      template:
        src: files/landing-page.html.j2
        dest: /usr/share/nginx/html/index.html

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp